var admin = require("firebase-admin");

var serviceAccount = require('./serviceAccountKey.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

// Function to create a document with error handling
async function createDocument(collection, data) {
    try {
      await db.collection(collection).add(data);
      console.log(`Document added to ${collection}`);
    } catch (error) {
      console.error(`Error adding document to ${collection}:`, error);
    }
  }

  createDocument('Users', {
    // "user_id": "user123", //Auto-generated by Firestore, not explicitly set
    "email": "testuser@example.com",
    "username": "TestUser",
    "bio": "This is a test user.",
    "pfp": "https://example.com/pfp.jpg",
    "followers": ["user456"], //Reference to user document
    "following": ["user789"], //Reference to user document
    "created_at": admin.firestore.FieldValue.serverTimestamp(),
    "updated_at": admin.firestore.FieldValue.serverTimestamp(),
    "posts": ["post1"], //Reference to post document
    "recipes": ["recipe1"] //Reference to recipe document
  }
    );  

    createDocument('Recipes', {
        // "recipe_id": "recipe1", //Auto-generated by Firestore, not explicitly set
        "author": {
          "user_id": "user123" //Reference to user document
        },
        "title": "Test Recipe",
        "media_url": "https://example.com/recipe.jpg",
        "ratings": 4.5,
        "isRecommended": true,
        "ingredients": [
          { "ingredient_id": "ing1", "quantity": "1 cup" }, //Contains reference to ingredient document
          { "ingredient_id": "ing2", "quantity": "2 tbsp" } //Contains reference to ingredient document
        ],
        "instructions": [
          "Step 1: Do this.",
          "Step 2: Do that."
        ],
        "tags": ["test", "recipe"],
        "comments": ["comment1"], //Reference to comment document
        "created_at": admin.firestore.FieldValue.serverTimestamp(),
        "updated_at": admin.firestore.FieldValue.serverTimestamp()
      }
      
    );      

    createDocument('Ingredients', {
        // "ingredient_id": "ing1", //Auto-generated by Firestore, not explicitly set
        "name": "Tomato"
      }
    );

    createDocument('Ingredients', {
        // "ingredient_id": "ing2",//Auto-generated by Firestore, not explicitly set
        "name": "Flour"
      }
    );
    
    createDocument('Fridges', {
        // "fridge_id": "fridge1", //Auto-generated by Firestore, not explicitly set
        "user_id": "user123", //Reference to user document
        "ingredients": [
          { "ingredient_id": "ing1"}, //Contains reference to ingredient document
          { "ingredient_id": "ing2"} //Contains reference to ingredient document
        ],
        "shopping_list": ["milk", "eggs"], //Contains references to ingredient document
        "updated_at": admin.firestore.FieldValue.serverTimestamp()
      }
    );      

    createDocument('Posts', {
        // "post_id": "post1", //Auto-generated by Firestore, not explicitly set
        "user_id": "user123", //Reference to user document
        "title": "Test Post",
        "description": "This is a test post.",
        "created_at": admin.firestore.FieldValue.serverTimestamp(),
        "comments": ["comment2"] //Reference to comment document
      }
    );     
    
    createDocument('Comments', {
        // "comment_id": "comment1", //Auto-generated by Firestore, not explicitly set
        "recipe_id": "recipe1", //Reference to recipe document
        "user_id": "user123", //Reference to user document
        "post_id": null, //Reference to post document
        "content": "This is a test comment.",
        "created_at": admin.firestore.FieldValue.serverTimestamp()
      }
      );

    createDocument('Ratings', {
        // "rating_id": "rating1", //Auto-generated by Firestore, not explicitly set
        "recipe_id": "recipe1", //Reference to recipe document
        "raters": [
            {
          "user_id": "user123", //Reference to user document
          "rating": 5, 
        }
    ],
        "avg_rating": 5
      }
    );